[versions]
spock = "2.4-groovy-4.0"
publish-plugin = "2.2.1"
graalvm-gradle-plugin = "1.1.12"

[libraries]
spock-core = { module = "org.spockframework:spock-core", version.ref = "spock" }
graalvm-plugin = { module = "org.graalvm.buildtools:native-gradle-plugin", version.ref = "graalvm-gradle-plugin" }

[plugins]
publish = { id = "com.gradle.plugin-publish", version.ref = "publish-plugin" }
