import com.uwyn.rife2.gradle.TemplateType

plugins {
    id("application")
    id("com.uwyn.rife2")
}

base {
    archivesName = "hello"
    version = 1.0
    group = "com.example"
}

application {
    mainClass = "hello.App"
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

repositories {
    mavenCentral()
}

rife2 {
    version = "1.10.1"
    useAgent = true
    precompiledTemplateTypes.add(TemplateType.HTML)
    templateDirectories.from(file("src/main/templates"))
}

dependencies {
    testImplementation("org.jsoup:jsoup:1.23.2")
    testImplementation(platform("org.junit:junit-bom:6.1.3"))
    testImplementation("org.junit.jupiter:junit-jupiter")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

tasks.named("test") {
    useJUnitPlatform()
}
